### PR TITLE
remove redundant code that might mess the string

### LINKED ISSUE #156: bug in anyMultibyteUTF8Characters()
The bug is in the following line
```
  if(Encoding(string) == "unknown")
    Encoding(string) <- encoding
```
here is a mini example that demo the bug:
```
> A <- "模式"
> Encoding(A)
[1] "unknown"
> Encoding(A) <- "UTF-8"
> A
[1] "ģʽ"
> enc2utf8(A)
[1] "ģʽ"
```
I think the above two lines could be remove, since `string <- enc2utf8(string)` does all needed.

### PR DESCRIPTION
**Pull request by jszhao**
Force encoding a string of unknown encoding will mess the string. And `enc2utf8` do the better. So the removed code is redundancy and might be harmful, and cause warning, such as:
```
Warning message:
In strsplit(string, "") : input string 1 is invalid UTF-8
```

Closes #156.

### CODE REVIEW

**Comment by jszhao** [comment]
it's a pull request to [https://github.com/yihui/tikzDevice/issues/156](https://github.com/yihui/tikzDevice/issues/156).

**Comment by jszhao** [comment]
I don't know why it not pass the checks.  I also don't know how to close this pull request. It seems that I have not remove the argument of `encoding="UTF-8"`, and I don't update the help page of the function.

**Comment by yihui** [comment]
Thanks! Don't worry about the failed test. I don't think it is relevant to your change.

@krlmlr Any ideas why it failed? https://travis-ci.org/yihui/tikzDevice/builds/218475233

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
