### PR TITLE
stop raster output from being resampled

### PR DESCRIPTION
**Pull request by smason**
this is in reference to issue #54

### CODE REVIEW

**Comment by krlmlr** [comment]
I'm now revisiting this code due to reentrance problems (#132), my approach is to write the raster "as is" using `png::writePNG()`, therefore obliterating the `tikzRasterResolution` option. Given that PGF is in full control of the final raster's dimensions and orientation, setting a DPI value in the created PNG file doesn't seem to be useful anyway. The only thing that's lost is a rescaling of raster images, but I guess nobody cares about that anyway -- if at all, it should affect only the file size of the output.

@smason: Do you think this makes sense?

**Comment by smason** [comment]
Yes, assuming I'm interpreting you correctly, it sounds reasonable.

Whenever I've sent a raster to output in R I've wanted it preserved exactly, and any resampling would be very undesirable.  Further, I've not noticed any other R device I've used resampling any raster given to it.

**Comment by krlmlr** [comment]
Thanks for your fast reply. I've noticed that R seems to be doing all the resampling it needs already: In particular, the [base_raster](https://github.com/yihui/tikzDevice/blob/master/tests/testthat/standard_graphs/base_raster.pdf) test looks almost unchanged when resampling is turned off; this was a pleasant surprise for me.

**Comment by krlmlr** [comment]
Wrong: It's done by PGF, via `interpolate=true`.

**Pull request merged**
